apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: kodega2016/expiration
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: nats://nats-cluster-ip-service:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: REDIS_HOST
            value: expiration-redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
