apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: kodega2016/orders
        env:
          - name: MONGO_URI
            value: mongodb://orders-mongo-cluster-ip-service:27017/orders
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: http://nats-cluster-ip-service:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-cluster-ip-service
spec:
  selector:
    app: orders
  ports:
  - name: orders
    protocol: TCP
    port: 3000
    targetPort: 3000
