name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: digital ocean k8s
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
