name: orders-auth
on:
  pull_request:
    paths:
      - 'orders/**'
    branches:
      - main
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: cd orders && npm install && npm run test:ci